In [2]:
import pandas as pd

In [5]:
df = pd.DataFrame({"sizes":["S","M","L","XL","M","S","L","M","S","XL","S","L","XXL","XL","S","L"]})
df.head(3)

  sizes
0     S
1     M
2     L

In [6]:
ord_data = [["S","M","L","XL","XXL"]]
ord_data

[['S', 'M', 'L', 'XL', 'XXL']]

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [15]:
# from Sklearn

ord = OrdinalEncoder(categories=ord_data)
ord.fit(df[["sizes"]])
df["en_sizes"]=ord.transform(df[["sizes"]])
df

   sizes  en_sizes
0      S       0.0
1      M       1.0
2      L       2.0
3     XL       3.0
4      M       1.0
5      S       0.0
6      L       2.0
7      M       1.0
8      S       0.0
9     XL       3.0
10     S       0.0
11     L       2.0
12   XXL       4.0
13    XL       3.0
14     S       0.0
15     L       2.0

In [16]:
# From map 

ord_data_map = {"S" : 2 ,"M": 4 ,"L" : 8 ,"XL" : 10 ,"XXL" : 12 }
ord_data_map

{'S': 2, 'M': 4, 'L': 8, 'XL': 10, 'XXL': 12}

In [19]:
df["en_sizes_map"] = df["sizes"].map(ord_data_map)
df

   sizes  en_sizes  en_sizes_map
0      S       0.0             2
1      M       1.0             4
2      L       2.0             8
3     XL       3.0            10
4      M       1.0             4
5      S       0.0             2
6      L       2.0             8
7      M       1.0             4
8      S       0.0             2
9     XL       3.0            10
10     S       0.0             2
11     L       2.0             8
12   XXL       4.0            12
13    XL       3.0            10
14     S       0.0             2
15     L       2.0             8